from rdflib.namespace import DefinedNamespace, Namespace
from rdflib.term import URIRef


class CEO(DefinedNamespace):
    """
    DESCRIPTION_EDIT_ME_!

    Generated from: SOURCE_RDF_FILE_EDIT_ME_!
    Date: 2026-04-01 08:47:37.061663
    """

    _NS = Namespace("https://linkeddata.cultureelerfgoed.nl/def/ceo#")

    ActorEnRol: URIRef  # Deze class representeert de associatie tussen een actor en een rol in de context van een gebeurtenis. This class represents the association between an actor and a role in the context of an event. De class ActorEnRol is de representatie van de actor en rol met betrekking tot een gebeurtenis. The class ActorEnRol is the representation of the actor and role with respect to an event.
    ArcheologischComplex: URIRef  # This class represents an archaeological complex related to cultural heritage. Deze class representeert een archeologisch complex met betrekking tot cultureel erfgoed. De class ArcheologischComplex is de representatie van een archeologisch complex met betrekking tot cultureel erfgoed. The class ArcheologischComplex is the representation of an archaeological complex related to cultural heritage.
    ArcheologischOnderzoeksgebied: URIRef  # This class represents a spatially bounded area in which archaeological research is carried out by the permit holder to conduct research. Deze class representeert een ruimtelijk begrensd gebied, waarin archeologisch onderzoek wordt uitgevoerd door de vergunninghouder tot het doen van onderzoek. De class ArcheologischOnderzoeksgebied is de representatie van een ruimtelijk begrensd gebied, waarin archeologisch onderzoek wordt uitgevoerd door de vergunninghouder tot het doen van onderzoek. The class ArcheologischOnderzoeksgebied is the representation of a spatially bounded area, in which archaeological research is carried out by the permit holder to conduct research.
    ArcheologischTerrein: URIRef  # This class represents a spatially defined area in which archaeological information is located. Deze class representeert een ruimtelijk begrensd gebied waarbinnen zich archeologische informatie bevindt. De class ArcheologischTerrein is de representatie van een ruimtelijk begrensd gebied waarbinnen zich archeologische informatie bevindt. The class ArcheologischTerrein is the representation of a spatially defined area in which archaeological information is located.
    BAGRelatie: URIRef  # This class represents recorded Basisregistratie Adressen en Gebouwen (BAG) pertaining to a cultural heritage object. Deze class representeert vastgelegde Basisregistratie Adressen en Gebouwen (BAG) met betrekking tot een cultuurhistorisch object. De class BAGRelatie is de representatie van vastgelegde Basisregistratie Adressen en Gebouwen (BAG) met betrekking tot een cultuurhistorisch object. The class BAGRelatie is the representation of recorded Basisregistratie Adressen en Gebouwen (BAG) pertaining to a cultural heritage object.
    BAGRelatienummer: URIRef  # Een uniek nummer dat wordt gebruikt om de BAG relatie instance te identificeren. A unique number used to identify the BAG relation instance. De property BAGRelatienummer wordt gebruikt om aan te geven het unieke nummer waaronder de BAG relatie instance bekend is. The property BAGRelationNumber is used to indicate the unique number under which the BAG relation instance is known.
    BRKRelatie: URIRef  # This class represents recorded Basisregistratie Kadaster (BRK) pertaining to a cultural heritage object. Deze class representeert vastgelegde Basisregistratie Kadaster (BRK) met betrekking tot een cultuurhistorisch object. De class BRKRelatie is de representatie van vastgelegde Basisregistratie Kadaster (BRK) met betrekking tot een cultuurhistorisch object. The class BRKRelatie is the representation of recorded Basisregistratie Kadaster (BRK) pertaining to a cultural heritage object.
    BRKRelatienummer: URIRef  # Een uniek nummer dat wordt gebruikt om de BRK relatie instance te identificeren. A unique number used to identify the BRK relation instance. De property BRKRelatienummer wordt gebruikt om aan te geven het unieke nummer waaronder de BRK relatie instance bekend is. The property BRKRelationNumber is used to indicate the unique number under which the BRK relation instance is known.
    BasisregistratieRelatie: URIRef  # This class represents the administrative recording of the relationship between a cultural heritage object and an entity in a base registration. Deze class representeert de administratieve vastlegging van de relatie tussen een cultuurhistorisch object en een instantie in een basisregistratie. De class BasisregistratieRelatie is de representatie van de administratieve vastlegging van de relatie tussen een cultuurhistorisch object en een instantie in een basisregistratie. The class BasisregistratieRelatie is the representation of the administrative recording of the relationship between a cultural heritage object and an entity in a base registration.
    BeginDatering: URIRef  # This class represents the start date of the time indication that a Cultural Heritage Object can have. Deze class representeert de begindatum van de tijdsaanduiding die een Cultuurhistorisch Object kan hebben. De class BeginDatering is de representatie van de begin datering van de tijdsaanduiding die een Cultuurhistorisch Object kan hebben. The class BeginDatering represents the start date of the time indication that a Cultural Heritage Object can have.
    BouwkundigeKwaliteit: URIRef  # De class BouwkundigeKwaliteit is een subclass van Kennisregistratie en is de representatie van de bouwkundige kwaliteit met betrekking tot een cultuurhistorisch object. The class BouwkundigeKwaliteit is a subclass of Kennisregistratie and represents the architectural quality associated with a cultural heritage object.
    Bronverwijzing: URIRef  # De class Bronverwijzing is een subclass van Kennisregistratie en vertegenwoordigt de bronverwijzing met betrekking tot een cultuurhistorisch object. The class Bronverwijzing is a subclass of Kennisregistratie and represents the reference to a source associated with a cultural heritage object. De class Bronverwijzing is een subclass van Kennisregistratie en is de representatie van de bronverwijzing met betrekking tot een cultuurhistorisch object.
    Complex: URIRef  # De class Complex is de representatie van beschrijvende of waarderende samenhang tussen rijksmonumenten, die als een complex zijn aangewezen. Deze samenhang is niet noodzakelijk voor de identificatie van die rijksmonumenten. The class Complex represents the descriptive or evaluative coherence between listed monuments that are designated as a complex. This coherence is not necessary for the identification of those listed monuments.
    CultuurhistorischObject: URIRef  # This class represents a phenomenon in reality with a certain cultural-historical value. Deze class representeert een fenomeen in de werkelijkheid met een zekere cultuurhistorische waarde. De class CultuurhistorischObject is de representatie van een fenomeen in de werkelijkheid met een zekere cultuurhistorische waarde. The class CultuurhistorischObject is the representation of a phenomenon in reality with a certain cultural-historical value.
    Datering: URIRef  # The class Datering represents the time indication associated with a Cultural Heritage Object. De class Datering is een representatie van de tijdsaanduiding die een Cultuurhistorisch Object kan hebben. The class Datering represents the time indication that a Cultural Heritage Object can have.
    EindDatering: URIRef  # The class EindDatering represents the end date of the time indication associated with a Cultural Heritage Object. De class EindDatering is de representatie van de eind datering van de tijdsaanduiding die een Cultuurhistorisch Object kan hebben. The class EindDatering represents the end date of the time indication that a Cultural Heritage Object can have.
    Functie: URIRef  # The class Functie is a subclass of kennisregistratie and represents the function associated with a cultural heritage object. De class Functie is een subclass van kennisregistratie en representeert de functie met betrekking tot een cultuurhistorisch object. De class Functie is een subclass van kennisregistratie en is de representatie van de functie met betrekking tot een cultuurhistorisch object.
    Gebeurtenis: URIRef  # The class Gebeurtenis is a subclass of kennisregistratie and represents recorded events associated with a cultural heritage object. De class Gebeurtenis is een subclass van kennisregistratie en representeert vastgelegde gebeurtenissen met betrekking tot een cultuurhistorisch object. De class Gebeurtenis is een subclass van kennisregistratie en is de representatie van vastgelegde gebeurtenissen met betrekking tot een cultuurhistorisch object.
    Geometrie: URIRef  # De class Geometrie is de representatie van de geometrie van een cultuurhistorisch object. The class Geometrie represents the geometry of a cultural heritage object.
    Gezicht: URIRef  # De class Gezicht is een representatie van een aangewezen, beschermd stads- en dorpsgezicht. The class Gezicht represents a designated, protected urban or village townscape.
    Grondsporen: URIRef  # De class Grondsporen is een representatie van een duidelijk begrensbaar verschijnsel van antropogene of natuurlijke oorsprong. The class Grondsporen represents a clearly delineated phenomenon of anthropogenic or natural origin.
    Kennisregistratie: URIRef  # De class Kennisregistratie is de representatie van vastgelegde kennis feiten met betrekking tot een cultuurhistorisch object. The class Kennisregistratie represents recorded knowledge facts associated with a cultural heritage object.
    LocatieAanduiding: URIRef  # De class LocatieAanduiding is de representatie van de locatie aanduiding met betrekking tot een cultuurhistorisch object. The class LocatieAanduiding represents the location indication associated with a cultural heritage object.
    Materiaal: URIRef  # De class Materiaal is een subclass van kennisregistratie en is de representatie van vastgelegde materialen met betrekking tot een cultuurhistorisch object. The class Materiaal is a subclass of kennisregistratie and represents recorded materials associated with a cultural heritage object.
    Naam: URIRef  # De class Naam is een subclass van kennisregistratie en is de representatie van vastgelegde namen met betrekking tot een cultuurhistorisch object. The class Naam is a subclass of kennisregistratie and represents recorded names associated with a cultural heritage object.
    Omschrijving: URIRef  # De class Omschrijving is een subclass van kennisregistratie en is de representatie van vastgelegde omschrijvingen met betrekking tot een cultuurhistorisch object. The class Omschrijving is a subclass of kennisregistratie and represents recorded descriptions associated with a cultural heritage object.
    Rijksdienst_voor_het_Cultureel_Erfgoed: URIRef  # 
    Rijksmonument: URIRef  # De class Rijksmonument is een representatie van onroerende cultuurhistorische objecten die als rijksmonument zijn aangewezen. The class Rijksmonument represents immovable cultural heritage objects designated as national monuments.
    StijlEnCultuur: URIRef  # De class StijlEnCultuur is een subclass van kennisregistratie en is de representatie van de stijl en cultuur met betrekking tot een cultuurhistorisch object. The class StijlEnCultuur is a subclass of kennisregistratie and represents the style and culture associated with a cultural heritage object.
    Type: URIRef  # De class Type is een subclass van kennisregistratie en is de representatie van vastgelegde typen met betrekking tot een cultuurhistorisch object. The class Type is a subclass of kennisregistratie and represents recorded types associated with a cultural heritage object.
    Vondsten: URIRef  # De class Vondsten is een representatie van alle soorten mobilia: roerende of roerend geraakte onderdelen van onroerende goederen, afkomstig van archeologisch veldwerk of archeologische collecties. The class Vondsten represents all kinds of mobilia: movable or movable-affected parts of immovable property, originating from archaeological fieldwork or archaeological collections.
    Vondstlocatie: URIRef  # De class Vondstlocatie is een representatie van geografisch begrensde gebieden, waar binnen min of meer aaneensluitend archeologisch sporen en/of vondsten zijn aangetroffen, eventueel van verschillende ouderdom. The class Vondstlocatie represents geographically bounded areas where contiguous or nearly contiguous archaeological traces and/or finds have been encountered, potentially of different ages.
    Werelderfgoed: URIRef  # De class Werelderfgoed is een representatie van een door het Werelderfgoedcomité van UNESCO op de Werelderfgoedlijst geplaatst cultuurhistorisch object. The class Werelderfgoed represents a cultural heritage object placed on the World Heritage List by the UNESCO World Heritage Committee.
    aantalGrondsporen: URIRef  # Een eigenschap om het aantal grondsporen aan te geven. A property used to indicate the number of traces. De property aantalGrondsporen wordt gebruikt om het aantal grondsporen aan te geven. The property aantalGrondsporen is used to indicate the number of traces.
    aantalVondsten: URIRef  # Een eigenschap die het aantal vondsten aangeeft. A property that indicates the number of finds. De property aantalVondsten wordt gebruikt om het aantal vondsten aan te geven. The property aantalVondsten is used to indicate the number of finds.
    actorEnRolnummer: URIRef  # Een uniek nummer dat wordt gebruikt om een specifieke actor en rol instance te identificeren. A unique number used to identify a specific actor and role instance. De property actorEnRolnummer wordt gebruikt om aan te geven het unieke nummer waaronder de actor en rol instance bekend is. The property actorEnRolnummer is used to indicate the unique number under which the actor and role instance is known.
    appartementAanduiding: URIRef  # De property appartementAanduiding wordt gebruikt om aan te geven of een appartement aanduiding aan een rijksmonument is gegeven. Voorbeelden van appartement aanduidingen zijn 9, 12A en B. The property appartementAanduiding is used to indicate whether an apartment designation has been assigned to a national monument. Examples of apartment designations include 9, 12A, and B. De property appartementAanduiding wordt gebruikt om aan te geven of een appartement aanduiding aan een rijksmonument is gegeven. The property appartementAanduiding is used to indicate whether an apartment designation has been assigned to a national monument.
    archis2Complexnummer: URIRef  # Dit is het complexnummer uit Archis 2 dat is gekoppeld aan een archeologisch complex of vondstlocatie. This is the complex number from Archis 2 that is linked to an archaeological complex or find location. De property archis2Complexnummer wordt gebruikt om aan te geven of een complexnummer uit Archis 2 aan een archeologisch complex of vondstlocatie is gekoppeld. The property archis2Complexnummer is used to indicate whether a complex number from Archis 2 is linked to an archaeological complex or find location.
    archis2Monumentnummer: URIRef  # Een uniek monumentnummer uit Archis 2 dat aan een archeologisch terrein is gekoppeld. Het identificeert het terrein in het Archis 2-systeem. A unique monument number from Archis 2 that is linked to an archaeological site. It identifies the site in the Archis 2 system. De property archis2Monumentnummer wordt gebruikt om aan te geven of een monumentnummer uit Archis 2 aan een archeologisch terrein is gekoppeld. The archis2Monumentnummer property is used to indicate whether a monument number from Archis 2 is linked to an archaeological site.
    archis2Vondstmeldingsnummer: URIRef  # De Archis2 vondstmeldingsnummer eigenschap geeft aan of een vondstmeldingsnummer uit Archis 2 aan een vondstlocatie is gekoppeld. Dit is een tekstuele eigenschap. The Archis2 discovery report number property indicates whether a discovery report number from Archis 2 is linked to a discovery location. This is a textual property. De property archis2Vondstmeldingsnummer wordt gebruikt om aan te geven of een vondstmeldingsnummer uit Archis 2 aan een vondstlocatie is gekoppeld. The archis2Vondstmeldingsnummer property is used to indicate whether a discovery report number from Archis 2 is linked to a discovery location.
    archis2Vondstnummer: URIRef  # Deze eigenschap geeft het vondstnummer uit Archis 2 aan dat aan een vondst of grondspoor is gekoppeld. This property indicates the Archis 2 discovery number linked to a find or ground trace. De property archis2Vondstnummer wordt gebruikt om aan te geven of een vondstnummer uit Archis 2 aan een vondst, grondspoor is gekoppeld. The property archis2Vondstnummer is used to indicate whether an Archis 2 discovery number is linked to a find, ground trace.
    archis2Waarnemingsnummer: URIRef  # De property archis2Waarnemingsnummer is een datatype property die wordt gebruikt om aan te geven of een waarnemingsnummer uit Archis 2 aan een vondstlocatie is gekoppeld. Het waarnemingsnummer wordt vaak gebruikt als referentie bij archeologische vondsten. The property archis2Waarnemingsnummer is a datatype property used to indicate whether an observation number from Archis 2 is linked to a find location. The observation number is often used as a reference for archaeological finds. De property archis2Waarnemingsnummer wordt gebruikt om aan te geven of een waarnemingsnummer uit Archis 2 aan een vondstlocatie is gekoppeld. The property archis2Waarnemingsnummer is used to indicate whether an observation number from Archis 2 is linked to a find location.
    basisregistratieRelatienummer: URIRef  # Een uniek nummer waarmee de basisregistratie relatie instance bekend is in de basisregistratie. A unique number through which the base registration relationship instance is known in the base registration. De property basisregistratieRelatienummer wordt gebruikt om aan te geven het unieke nummer waaronder de basisregistratie relatie instance bekend is. The property basisregistratieRelatienummer is used to indicate the unique number under which the base registration relationship instance is known.
    begrenzingsdatumGezicht: URIRef  # This property specifies the date on which the boundary of the townscape is determined. Deze eigenschap geeft de datum aan waarop de begrenzingsdatum van het Gezicht is vastgesteld. De property begrenzingsdatumGezicht wordt gebruikt om aan te geven wanneer de begrenzingsdatum van het Gezicht is vastgesteld. The property begrenzingsdatumGezicht is used to indicate when the boundary of the townscape is determined.
    bevatObject: URIRef  # De property bevatObject legt de relatie tussen de ligging van een cultuurhistorisch object met betrekking tot een cultuurhistorisch object vast. The bevatObject property establishes the relationship between the location of a cultural heritage object and a cultural heritage object.
    bijzonderGebied: URIRef  # Een bijzonder gebied is een gebied in een stad of dorp met een uitzonderlijk cultureel en historisch belang. Deze property geeft aan of een beschermd stads- of dorpsgezicht als bijzonder gebied wordt beschouwd. A special area is an area in a city or village with exceptional cultural and historical significance. This property indicates whether a protected city or village view (townscape) is considered a special area. De property bijzonderGebied wordt gebruikt om aan te geven dat een beschermd stads- of dorpsgezicht een gebied in een stad of dorp is met een bijzonder cultuurhistorisch karakter. The property bijzonderGebied is used to indicate that a protected city or village view is an area in a city or village (townscape) with a special cultural-historical character.
    complexnummer: URIRef  # De property complexnummer wordt gebruikt om aan te geven het unieke nummer waaronder het complex van rijksmonumenten bekend is in het monumentenregister. The property complexnummer is used to indicate the unique number under which the complex of national monuments is known in the monument register.
    cultuurhistorischObjectnummer: URIRef  # Elk cultuurhistorisch object dat wordt erkend en geregistreerd door de RCE, krijgt een uniek objectnummer toegewezen. Dit objectnummer dient als een identificatienummer voor het betreffende object in de registratiedatabase van de RCE. Each cultural historical object recognized and registered by the RCE is assigned a unique object number. This object number serves as an identification number for the respective object in the registration database of the RCE. De property cultuurhistorischObjectnummer wordt gebruikt om aan te geven of een cultuurhistorischObjectnummer aan een Cultuurhistorisch object is gegeven. The cultuurhistorischObjectnummer property is used to indicate whether a cultuurhistorischObjectnummer has been assigned to a Cultural Historical object.
    dateringnummer: URIRef  # Een uniek nummer dat wordt gebruikt om de datering instance te identificeren. Het kan worden gebruikt om de datering in een database te zoeken of te koppelen aan andere gerelateerde informatie. A unique number used to identify the dating instance. It can be used to query the dating in a database or link it to other related information. De property dateringnummer wordt gebruikt om aan te geven het unieke nummer waaronder de datering instance bekend is. The property dateringnummer is used to indicate the unique number under which the dating instance is known.
    datum: URIRef  # Een eigenschap om de datum van een begin- of een einddatering aan te geven. A property to indicate the date of a start or end date. De property datum wordt gebruikt om aan te geven de datum van een begin- of een einddatering. The property datum is used to indicate the date of a start or end date.
    datumInschrijvingInMonumentenregister: URIRef  # De property datumInschrijvingInMonumentenregister wordt gebruikt om aan te geven onder welk uniek nummer het rijksmonument bekend is in het monumentenregister. The property datumInschrijvingInMonumentenregister is used to indicate the unique number under which the national monument is known in the monument register. De datum van inschrijving in het monumentenregister is een registergegeven binnen de class Rijksmonument. The date of registration in the monument register is a registry item within the Rijksmonument class.
    formeelStandpunt: URIRef  # Een formeel standpunt van de kennisregistratie. A formal standpoint of the knowledge registration. De property formeelstandpunt wordt gebruikt om aan te geven of de kennisregistratie een formeel standpunt betreft. The property formeelstandpunt is used to indicate whether the knowledge registration concerns a formal standpoint.
    gemeentecode: URIRef  # Dit is de gemeentecode van het rijksmonument. This is the municipality code of the national monument. De property BRK gemeenteCode wordt gebruikt om aan te geven welke gemeente code is gekoppeld aan het rijksmonument. The BRK gemeenteCode property is used to indicate which municipality code is linked to the national monument.
    gemeentenaam: URIRef  # Een datatype-eigenschap in het BRK vocabulaire om de naam van de gemeente aan te geven waaraan het rijksmonument is gelegen. A datatype property in the BRK vocabulary used to indicate the name of the municipality where the national monument is located. De property BRK gemeentenaam wordt gebruikt om aan te geven welke gemeentenaam is gekoppeld aan het rijksmonument. The BRK gemeentenaam property is used to indicate which municipality name is linked to the national monument.
    geometriebesluit: URIRef  # Eigenschap die de besluitstatus van de geometrie aangeeft. Property indicating the decision status of the geometry. De property geometriebesluit wordt gebruikt om aan te geven de besluit status van de geometrie. The property geometriebesluit is used to indicate the decision status of the geometry.
    geometrienummer: URIRef  # Deze eigenschap geeft het unieke geometrienummer van de geometrie instance weer. This property represents the unique geometry number of the geometry instance. De property geometrienummer wordt gebruikt om aan te geven het unieke nummer waaronder de geometrie instance bekend is. The property geometrienummer is used to indicate the unique number under which the geometry instance is known.
    gezichtsnummer: URIRef  # Een gezichtsnummer is een uniek nummer dat wordt gebruikt om een specifiek stads- of dorpsgezicht te identificeren. A gezichtsnummer is a unique number used to identify a specific urban or village townscape. De property gezichtsnummer wordt gebruikt om aan te geven het unieke nummer waaronder het stads- of dorpsgezicht bekend is. The property gezichtsnummer is used to indicate the unique number under which the urban or village townscape is known.
    heeftActor: URIRef  # Een eigenschap die de relatie vastlegt tussen een actor en een rol, en de actor in relatie tot een cultuurhistorisch object. A property that establishes the relationship between an actor and a role, and the actor in relation to a cultural heritage object. De property heeftActor legt de relatie tussen de actor en rol en de actor met betrekking tot een cultuurhistorisch object vast. The property heeftActor establishes the relationship between the actor and role, and the actor in relation to a cultural heritage object.
    heeftActorEnRol: URIRef  # Een eigenschap om de relatie tussen een gebeurtenis en de betrokken acteur en rol vast te leggen in verband met een cultureel erfgoedobject. A property to establish the relationship between an event and the involved actor and role related to a cultural heritage object. De property heeftActorEnRol legt de relatie tussen de gebeurtenis en de actor en zijn rol met betrekking tot een cultuurhistorisch object vast. The property heeftActorEnRol establishes the relationship between the event and the actor and their role related to a cultural heritage object.
    heeftArcheologischeWaardering: URIRef  # Deze eigenschap wordt gebruikt om de archeologische waardering van een archeologisch terrein aan te geven. This property is used to indicate the archaeological valuation of an archaeological site. De property heeftArcheologischeWaardering legt de relatie tussen het archeologisch terrein en de archeologische waardering vast. The property heeftArcheologischeWaardering establishes the relationship between the archaeological site and the archaeological valuation.
    heeftBAGRelatie: URIRef  # Een eigenschap die de relatie tussen de basisregistratie en de BAG relatie definieert. A property that defines the relationship between the base registration and the BAG relationship. De property heeftBAGRelatie legt de relatie tussen de basisregistratie en de BAG relatie vast. The property heeftBAGRelatie establishes the relationship between the base registration and the BAG relationship.
    heeftBRKRelatie: URIRef  # De eigenschap heeftBRKRelatie legt de relatie vast tussen de basisregistratie en de Basisregistratie Kadaster (BRK) relatie. Deze eigenschap wordt gebruikt om informatie over de relatie tussen de basisregistratie en de BRK relatie vast te leggen. The heeftBRKRelatie property establishes the relationship between the base registration and the Base Registration Cadastre (BRK) relationship. This property is used to capture information about the relationship between the base registration and the BRK relationship. De property heeftBRKRelatie legt de relatie tussen de basisregistratie en de BRK relatie vast. The heeftBRKRelatie property establishes the relationship between the base registration and the BRK relationship.
    heeftBasisregistratieRelatie: URIRef  # De property heeftBasisregistratieRelatie legt de relatie tussen het cultuurhistorisch object en de basisregistratie relatie vast. The property heeftBasisregistratieRelatie establishes the relationship between the cultural heritage object and the base registration relationship.
    heeftBebouwdeKomType: URIRef  # De eigenschap heeftBebouwdeKomType legt de relatie tussen het rijksmonument en het type bebouwde kom vast. Het beschrijft het soort bebouwde kom waarin het rijksmonument zich bevindt. The heeftBebouwdeKomType property establishes the relationship between the national monument and the built-up area type. It describes the type of built-up area in which the national monument is located. De property heeftBebouwdeKomtype legt de relatie tussen het rijksmonument en het bebouwde kom type vast. The property heeftBebouwdeKomType establishes the relationship between the national monument and the built-up area type.
    heeftBeginDatering: URIRef  # Deze property legt de relatie tussen een bepaalde datering en de begindatering van een object vast. Het wordt gebruikt om informatie over de begindatum van een object vast te leggen. This property establishes the relationship between a specific date and the start date of an object. It is used to capture information about the start date of an object. De property heeftBeginDatering legt de relatie tussen de datering en de begindatering vast. The property heeftBeginDatering establishes the relationship between the date and the start date.
    heeftBetrekkingOp: URIRef  # De property heeftBetrekkingOp legt de relatie tussen de kennisregistratie en het cultuurhistorisch object vast. Het wordt gebruikt om aan te geven dat een specifieke kennisregistratie betrekking heeft op een bepaald cultuurhistorisch object. The has relation to property establishes the relationship between the knowledge registration and the cultural heritage object. It is used to indicate that a specific knowledge registration has relation to a particular cultural heritage object. De property heeftBetrekkingOp legt de relatie tussen de kennisregistratie en het cultuurhistorisch object vast. The property heeftBetrekkingOp establishes the relationship between the knowledge registration and the cultural heritage object.
    heeftBetrouwbaarheid: URIRef  # De property heeftBetrouwbaarheid legt de relatie tussen de datering en de mate van betrouwbaarheid vast. Het wordt gebruikt om aan te geven hoe betrouwbaar een bepaalde datering is. The property heeftBetrouwbaarheid establishes the relationship between the dating and the degree of reliability. It is used to indicate how reliable a certain dating is. De property heeftBetrouwbaarheid legt de relatie tussen de datering en de mate van betrouwbaarheid vast. The property heeftBetrouwbaarheid establishes the relationship between the dating and the degree of reliability.
    heeftBouwkundigeKwaliteit: URIRef  # De property heeftBouwkundigeKwaliteit legt de relatie tussen een cultuurhistorisch object en de bouwkundige kwaliteit vast. Het beschrijft of het object een goede bouwkundige staat heeft. The property heeftBouwkundigeKwaliteit establishes the relationship between a cultural heritage object and its architectural quality. It describes whether the object is in good architectural condition. De property heeftBouwkundigeKwaliteit legt de relatie tussen een cultuurhistorisch object en de bouwkundige kwaliteit vast. The property heeftBouwkundigeKwaliteit establishes the relationship between a cultural heritage object and its architectural quality.
    heeftBouwkundigeStaat: URIRef  # Deze eigenschap legt de relatie tussen de BouwkundigeKwaliteit en de bouwkundige staat van een cultuurhistorisch object vast. This property establishes the relationship between the BouwkundigeKwaliteit and the architectural state of a cultural heritage object. De property heeftBouwkundigeStaat legt de relatie tussen de BouwkundigeKwaliteit en de bouwkundige staat met betrekking tot een cultuurhistorisch object vast. The property heeftBouwkundigeStaat establishes the relationship between the BouwkundigeKwaliteit and the architectural state of a cultural heritage object.
    heeftDatering: URIRef  # De property heeftDatering legt de relatie tussen een gebeurtenis en de datering met betrekking tot een cultuurhistorisch object vast. Het wordt gebruikt om de datering van een cultuurhistorisch object te beschrijven in relatie tot een gebeurtenis. The hasDating property establishes the relationship between an event and the dating of a cultural heritage object. It is used to describe the dating of a cultural heritage object in relation to an event. De property heeftDatering legt de relatie tussen een gebeurtenis en de datering met betrekking tot een cultuurhistorisch object vast. The property heeftDatering establishes the relationship between an event and the dating of a cultural heritage object.
    heeftDateringsmethode: URIRef  # De property heeftDatering legt de relatie tussen een gebeurtenis en de dateringsmethode vast. The heeftDateringsmethode property establishes the relationship between an event and the dating method.
    heeftEindDatering: URIRef  # De property heeftBeginDatering legt de relatie tussen de datering en de einddatering vast. The heeftEindDatering property establishes the relationship between the date and the end date.
    heeftFunctie: URIRef  # De property heeftFunctie legt de relatie vast tussen een cultuurhistorisch object en de functie ervan. Dit kan helpen bij het begrijpen van de betekenis en het gebruik van het object. The property heeftFunctie establishes the relationship between a cultural-historical object and its function. This can help in understanding the meaning and use of the object. De property heeftFunctie legt de relatie tussen een cultuurhistorisch object en de functie vast. The property heeftFunctie establishes the relationship between a cultural-historical object and its function.
    heeftFunctieNaam: URIRef  # Deze eigenschap legt de relatie vast tussen een functie en de naam van de functie. This property establishes the relationship between a function and its name. De property heeftFunctienaam legt de relatie tussen de functie en de naam van de functie vast. The property heeftFunctieNaam establishes the relationship between the function and its name.
    heeftGebeurtenis: URIRef  # Deze property legt de relatie tussen een cultuurhistorisch object en de gebeurtenis vast. Het wordt gebruikt om aan te geven welke gebeurtenis verband houdt met het object. This property establishes the relationship between a cultural heritage object and the event. It is used to indicate which event is associated with the object. De property heeftGebeurtenis legt de relatie tussen een cultuurhistorisch object en de gebeurtenis vast. The property heeftGebeurtenis establishes the relationship between a cultural heritage object and the event.
    heeftGebeurtenisNaam: URIRef  # De eigenschap heeftGebeurtenisNaam legt de relatie tussen de gebeurtenis en de naam van de gebeurtenis vast. De gebeurtenis heeft een naam die wordt vastgelegd met behulp van deze eigenschap. The property heeftGebeurtenisNaam establishes the relationship between the event and the name of the event. The event has a name that is captured using this property. De property heeftGebeurtenisNaam legt de relatie tussen de gebeurtenis en de naam van de gebeurtenis vast. The property heeftGebeurtenisNaam establishes the relationship between the event and the name of the event.
    heeftGemeente: URIRef  # De property heeftGemeente wordt gebruikt om de relatie tussen een cultuurhistorisch object en de gemeente waarin het object zich bevindt aan te geven. Het is een registergegeven binnen de class Rijksmonument. The property heeftGemeente is used to indicate the relationship between a cultural heritage object and the municipality in which the object is located. It is a registry entry within the class Rijksmonument. De property heeftGemeente is een registergegeven binnen de class Rijksmonument. The property heeftGemeente is a registry entry within the class Rijksmonument. De property heeftGemeente legt de relatie tussen de basisregistratie relatie van een cultuurhistorisch object en de gemeente waarin het cultuurhistorisch object zich bevindt. The property heeftGemeente establishes the relationship between the base registration relationship of a cultural heritage object and the municipality in which the cultural heritage object is located.
    heeftGeometrie: URIRef  # De eigenschap heeftGeometrie legt de relatie tussen een cultuurhistorisch object en de geometrie vast. Het wordt gebruikt om aan te geven dat een cultuurhistorisch object een bepaalde geometrie heeft. The property heeftGeometrie establishes the relationship between a cultural heritage object and its geometry. It is used to indicate that a cultural heritage object has a certain geometry. De property heeftGeometrie legt de relatie tussen een cultuurhistorisch object en de geometrie vast.
    heeftGeometrieKwaliteit: URIRef  # De property heeftGeometrieKwaliteit legt de relatie tussen de geometrie en de geometrische kwaliteit vast. The property heeftGeometrieKwaliteit establishes the relationship between geometry and geometric quality.
    heeftGeometrieStatus: URIRef  # De property heeftGeometrieStatus legt de relatie tussen de geometrie en de geometrische status vast. Het beschrijft de status van de geometrie. The property heeftGeometrieStatus establishes the relationship between the geometry and the geometric status. It describes the status of the geometry. De property heeftGeometrieStatus legt de relatie tussen de geometrie en de geometrische status vast. The property heeftGeometrieStatus establishes the relationship between the geometry and the geometric status.
    heeftGeometrieType: URIRef  # This property relates a cultural-historical object to its geometry type. Deze eigenschap relateert een cultuurhistorisch object aan zijn geometrietype. De property heeftGeometrieType legt de relatie tussen een cultuurhistorisch object en de geometrie type vast. The property heeftGeometrieType establishes the relationship between a cultural-historical object and its geometry type.
    heeftGezichtsstatus: URIRef  # De property heeftGezichtsstatus legt de relatie tussen het gezicht en het gezichtsstatus vast. Het beschrijft of het gezicht een bepaalde status heeft, zoals erfgoedwaarde, beschermd monument, etc. The property heeftGezichtsstatus establishes the relationship between the townscape and the townscape status. It describes whether the townscape has a certain status, such as heritage value, protected monument, etc. De property heeftGezichtsstatus legt de relatie tussen het gezicht en het gezichtsstatus vast. The property heeftGezichtsstatus establishes the relationship between the townscape and the townscape status.
    heeftHerkomst: URIRef  # Deze eigenschap legt de relatie tussen de geometrie en de herkomst vast. Het geeft aan waar de geometrie vandaan komt. This property establishes the relationship between the geometry and the origin. It indicates where the geometry comes from. De property heeftHerkomst legt de relatie tussen de geometrie en de herkomst vast. The property heeftHerkomst establishes the relationship between the geometry and the origin.
    heeftHoofdobject: URIRef  # De property heeftHoofdobject legt de relatie tussen het complex en het hoofdobject met betrekking tot een rijksmonument vast. Het hoofdobject is het belangrijkste object binnen het complex en is van nationaal belang. The property heeftHoofdobject establishes the relationship between the complex and the main object regarding a national monument. The main object is the most significant object within the complex and holds national importance. De property heeftHoofdobject legt de relatie tussen het complex en het hoofdobject met betrekking tot een rijksmonument vast. The property heeftHoofdobject establishes the relationship between the complex and the main object regarding a national monument.
    heeftHuidigeFunctie: URIRef  # De property heeftHuidigeFunctie legt de relatie tussen een cultuurhistorisch object en de huidige functie vast. Dit attribuut wordt gebruikt om informatie vast te leggen over de huidige functie van een specifiek Rijksmonument. The property heeftHuidigeFunctie establishes the relationship between a cultural heritage object and its current function. This attribute is used to capture information about the current function of a specific national monument. De property heeftHuidigeFunctie legt de relatie tussen een cultuurhistorisch object en de huidige functie vast. The property heeftHuidigeFunctie establishes the relationship between a cultural heritage object and its current function.
    heeftIndicatieNauwkeurigheid: URIRef  # Heeft indicatie nauwkeurigheid: Deze eigenschap legt de relatie tussen de datering en de indicatie nauwkeurigheid vast. Has indication accuracy: This property establishes the relationship between the dating and the indication accuracy. De property heeftIndicatieNauwkeurigheid legt de relatie tussen de datering en de indicatie nauwkeurigheid vast. The property heeftIndicatieNauwkeurigheid establishes the relationship between the dating and the indication accuracy.
    heeftJuridischeStatus: URIRef  # De property heeftJuridischeStatus legt de relatie tussen het rijksmonument en de juridische status. Het geeft aan of het rijksmonument voorbeschermd is of een officieel rijksmonument is. The property heeftJuridischeStatus defines the relationship between the national monument and its legal status. It indicates whether the national monument is pre-protected or an officially listed national monument. De property heeftJuridischeStatus legt de relatie het rijksmonument en de juridische status, geeft aan of het rijksmonument voorbeschermd of rijksmonument is. The property heeftJuridischeStatus defines the relationship between the national monument and its legal status, indicating whether the national monument is pre-protected or listed.
    heeftKennisdomein: URIRef  # De property heeftKennisdomein legt de relatie tussen de kennisregistratie en het kennisdomein vast. Het beschrijft welk kennisdomein aan een specifieke kennisregistratie is gekoppeld. The property heeftKennisdomein establishes the relationship between knowledge registration and the knowledge domain. It describes which knowledge domain is associated with a specific knowledge registration. De property heeftKennisdomein legt de relatie tussen de kennisregistratie en het kennisdomein vast. The property heeftKennisdomein establishes the relationship between knowledge registration and the knowledge domain.
    heeftKennisregistratie: URIRef  # De property heeftKennisregistratie legt de relatie tussen het cultuurhistorisch object en de Kennisregistratie vast. Het geeft aan dat het cultuurhistorisch object is geregistreerd in de Kennisregistratie. The property heeftKennisregistratie establishes the relationship between the cultural heritage object and the Knowledge Registration. It indicates that the cultural heritage object is registered in the Knowledge Registration. De property heeftKennisregistratie legt de relatie tussen het cultuurhistorisch object en de Kennisregistratie vast. The property heeftKennisregistratie establishes the relationship between the cultural heritage object and the Knowledge Registration.
    heeftLocatieAanduiding: URIRef  # De property heeftLocatieAanduiding legt de relatie tussen het cultuurhistorisch object en de locatie aanduiding vast. Het wordt gebruikt om de specifieke locatie of plaats van het object aan te geven. The property heeftLocatieAanduiding establishes the relationship between the cultural heritage object and the location indication. It is used to specify the specific location or place of the object. De property heeftLocatieAanduiding legt de relatie tussen het cultuurhistorisch object en de locatie aanduiding vast. The property heeftLocatieAanduiding establishes the relationship between the cultural heritage object and the location indication.
    heeftLocatieAanduidingStatus: URIRef  # De property heeftLocatieAanduidingStatus legt de relatie tussen de locatie aanduiding en de status van de locatie Aanduiding met betrekking tot een cultuurhistorisch object vast. The property heeftLocatieAanduidingStatus establishes the relationship between the location indication and the status of the location indication with respect to a cultural heritage object.
    heeftMateriaal: URIRef  # De property heeftMateriaal legt de relatie tussen een cultuurhistorisch object en het materiaal vast. Het wordt gebruikt om aan te geven van welk materiaal een object is gemaakt. The property heeftMateriaal establishes the relationship between a cultural heritage object and its material. It is used to indicate the material from which an object is made. De property heeftMateriaal legt de relatie tussen een cultuurhistorisch object en het materiaal vast. The property heeftMateriaal establishes the relationship between a cultural heritage object and its material.
    heeftMateriaalNaam: URIRef  # De property heeftMateriaalNaam legt de relatie tussen het materiaal en de naam van het materiaal vast. Het wordt gebruikt om de naam van het materiaal te definiëren. The property heeftMateriaalNaam establishes the relationship between the material and its name. It is used to define the name of the material. De property heeftMateriaalNaam legt de relatie tussen het materiaal en de naam van het materiaal vast. The property heeftMateriaalNaam establishes the relationship between the material and its name.
    heeftMonumentAard: URIRef  # De property heeftMonumentAard legt de relatie tussen een rijksmonument en de aard van het monument vast, geeft aan of het rijksmonument archeologisch of onroerend gebouwd is. Voorbeeld: <https://data.cultureelerfgoed.nl/term/id/rn/fc966a68-8863-4970-a83e-110f96006c21>. The property heeftMonumentAard establishes the relationship between a national monument and the nature of the monument, indicating whether the national monument is archaeological or immovable. Example: <https://data.cultureelerfgoed.nl/term/id/rn/fc966a68-8863-4970-a83e-110f96006c21>. De property heeftMonumentAard legt de relatie tussen een rijksmonument en de aard van het monument vast, geeft aan of het rijksmonument archeologisch of onroerend gebouwd is. The property heeftMonumentAard establishes the relationship between a national monument and the nature of the monument, indicating whether the national monument is archaeological or immovable.
    heeftNaam: URIRef  # De property heeftNaam legt de relatie tussen een cultuurhistorisch object en de naam vast. Het wordt gebruikt om de naam van een cultuurhistorisch object vast te leggen. The property heeftNaam establishes the relationship between a cultural heritage object and its name. It is used to capture the name of a cultural heritage object. De property heeftNaam legt de relatie tussen een cultuurhistorisch object en de naam vast. The property heeftNaam establishes the relationship between a cultural heritage object and its name.
    heeftObservatiedatum: URIRef  # De property heeftObservatiedatum legt de relatie tussen de Kennisregistratie en de observatiedatum van de registratie vast. Deze eigenschap wordt gebruikt om de datum van een observatie vast te leggen in een kennisregistratie. The property heeftObservatiedatum establishes the relationship between the Knowledge Registration and the observation date of the registration. This property is used to capture the date of an observation in a knowledge registration. De property heeftObservatiedatum legt de relatie tussen de Kennisregistratie en de observatiedatum van de registratie vast. The property heeftObservatiedatum establishes the relationship between the Knowledge Registration and the observation date of the registration.
    heeftOmschrijving: URIRef  # De property heeftOmschrijving legt de relatie tussen een cultuurhistorisch object en de omschrijving vast. Het wordt gebruikt om een beschrijving toe te kennen aan een specifiek object. The property heeftOmschrijving establishes the relationship between a cultural heritage object and its description. It is used to assign a description to a specific object. De property heeftOmschrijving legt de relatie tussen een cultuurhistorisch object en de omschrijving vast. The property heeftOmschrijving establishes the relationship between a cultural heritage object and its description.
    heeftOmschrijvingstype: URIRef  # De property heeftOmschrijvingstype legt de relatie tussen de omschrijving en de type omschrijving met betrekking tot een cultuurhistorisch object vast. Deze eigenschap wordt gebruikt om een bepaald type omschrijving te associëren met een specifieke omschrijving van een cultuurhistorisch object. The property heeftOmschrijvingstype establishes the relationship between the description and the type of description concerning a cultural heritage object. This property is used to associate a specific type of description with a particular description of a cultural heritage object. De property heeftOmschrijvingstype legt de relatie tussen de omschrijving en de type omschrijving met betrekking tot een cultuurhistorisch object vast. The property heeftOmschrijvingstype establishes the relationship between the description and the type of description concerning a cultural heritage object.
    heeftOndergrondGezicht: URIRef  # This property establishes the relationship between the layer of the map and the townscape. Deze eigenschap legt de relatie vast tussen de ondergrond van de kaartlaag en het Gezicht. De property heeftOndergrondGezicht legt de relatie tussen de ondergrond van de kaartlaag en het Gezicht vast.
    heeftOorspronkelijkeFunctie: URIRef  # De property heeftOorspronkelijkeFunctie legt de relatie tussen een cultuurhistorisch object en de oorspronkelijke functie vast. Het beschrijft de oorspronkelijke functie van een rijksmonument. The property heeftOorspronkelijkeFunctie establishes the relationship between a cultural heritage object and its original function. It describes the original function of a national monument. De property heeftOorspronkelijkeFunctie legt de relatie tussen een cultuurhistorisch object en de oorspronkelijke functie vast. The property heeftOorspronkelijkeFunctie establishes the relationship between a cultural heritage object and its original function.
    heeftPand: URIRef  # De heeftPand property verwijst naar een specifiek pand in de Basisregistratie Adressen en Gebouwen. Het is een objectproperty gemaakt op 17 juni 2022. The heeftPand property refers to a specific building in the Basisregistratie Adressen en Gebouwen. It is an object property created on June 17, 2022. De property heeftPand verwijst naar pandidentificatie uit de Basisregistratie Adressen en Gebouwen. The heeftPand property refers to building identification from the Basisregistratie Adressen en Gebouwen.
    heeftPeriode: URIRef  # De property heeftPeriode legt de relatie tussen de datering en de periode vast. Het definieert dat een bepaalde datering een bepaalde periode omvat. The property heeftPeriode establishes the relationship between the dating and the period. It defines that a certain dating encompasses a certain period. De property heeftPeriode legt de relatie tussen de datering en de periode vast. The property heeftPeriode establishes the relationship between the dating and the period.
    heeftProvincie: URIRef  # De property heeftProvincie wordt gebruikt om de relatie tussen een cultuurhistorisch object en de provincie waarin het object zich bevindt aan te geven. Het is een registergegeven binnen de class Rijksmonument. The property heeftProvincie is used to indicate the relationship between a cultural heritage object and the province in which the object is located. It is a registry entry within the class Rijksmonument. De property heeftProvincie legt de relatie tussen de BasisRegistratieRelatie van een cultuurhistorisch object en de provincie waarin het cultuurhistorisch object zich bevindt. The property heeftProvincie establishes the relationship between the BaseRegistratieRelatie of a cultural heritage object and the province in which the cultural heritage object is located.
    heeftRijksmonument: URIRef  # Een complex heeft een relatie met een specifiek rijksmonument. Deze property legt die relatie vast. A complex has a relationship with a specific national monument. This property establishes that relationship. De property heeftSamenhang legt de relatie tussen het complex met betrekking tot een rijksmonument vast. The property heeftSamenhang establishes the relationship between the complex and a national monument.
    heeftRol: URIRef  # De property heeftRol legt de relatie vast tussen de actor en rol, en de rol met betrekking tot een cultuurhistorisch object. The heeftRol property establishes the relationship between the actor and role, and the role with respect to a cultural heritage object. De property heeftRol legt de relatie tussen de actor en rol en de rol met betrekking tot een cultuurhistorisch object vast. The property heeftRol establishes the relationship between the actor and role, and the role with respect to a cultural heritage object.
    heeftSituering: URIRef  # De property heeftSituering legt de relatie tussen een rijksmonument dat geen verblijfsobject in de Basisregistratie Adressen en Gebouwen (BAG) is met een verblijfsobject in de BAG. Het wordt gebruikt om aan te geven waar een rijksmonument gelegen is ten opzichte van een verblijfsobject. The property heeftSituering establishes the relationship between a national monument that is not a dwelling object in the Basisregistratie Adressen en Gebouwen (BAG) and a dwelling object in the BAG. It is used to indicate the location of a national monument in relation to a dwelling object. De property heeftSituering legt de relatie tussen een rijksmonument dat geen verblijfsobject in de BAG is met een verblijfsobject in de BAG. The property heeftSituering establishes the relationship between a national monument that is not a dwelling object in the BAG and a dwelling object in the BAG.
    heeftStijlEnCultuur: URIRef  # De property heeftStijlEnCultuur legt de relatie tussen een cultuurhistorisch object en de stijl en cultuur vast. Voorbeelden van objecten die deze relatie kunnen hebben zijn te vinden op [link naar voorbeeld]. De property is gecreëerd op 28 juni 2018. The property heeftStijlEnCultuur establishes the relationship between a cultural heritage object and the style and culture. Examples of objects that can have this relationship can be found at [link to example]. The property was created on June 28, 2018. De property heeftStijlEnCultuur legt de relatie tussen een cultuurhistorisch object en de stijl en cultuur vast. The property heeftStijlEnCultuur establishes the relationship between a cultural heritage object and the style and culture.
    heeftStijlEnCultuurNaam: URIRef  # De property heeftStijlEnCultuurNaam legt de relatie tussen de stijl en cultuur en de naam van de stijl en cultuur vast. Het vertegenwoordigt de naam van een specifieke stijl en cultuur. The property heeftStijlEnCultuurNaam establishes the relationship between the style and culture and the name of the style and culture. It represents the name of a specific style and culture. De property heeftStijlEnCultuurNaam legt de relatie tussen de stijl en cultuur en de naam van de stijl en cultuur vast. The property heeftStijlEnCultuurNaam establishes the relationship between the style and culture and the name of the style and culture.
    heeftTemporeleRelatie: URIRef  # De property heeftTemporeleRelatie legt de relatie tussen het historische tijdperk met betrekking tot een cultuurhistorisch object vast. The property heeftTemporeleRelatie defines the relationship between historical period regarding a cultural heritage object. The property heeftTemporeleRelatie defines the relationship between the historical period regarding a cultural heritage object.
    heeftToestand: URIRef  # De property heeftToestand legt de relatie tussen de vondst en de toestand vast. Voorbeeld: <https://data.cultureelerfgoed.nl/term/id/rn/0a4eaca3-4dd3-48ad-a472-da658b2a6975>. The property heeftToestand establishes the relationship between the find and the condition. Example: <https://data.cultureelerfgoed.nl/term/id/rn/0a4eaca3-4dd3-48ad-a472-da658b2a6975>. De property heeftToestand legt de relatie tussen de vondst en de toestand vast. The property heeftToestand establishes the relationship between the find and the condition.
    heeftType: URIRef  # De property heeftType legt de relatie tussen een cultuurhistorisch object en het type vast. Dit kan bijvoorbeeld worden gebruikt om aan te geven dat een object het type beeldhouwwerk heeft. The property heeftType establishes the relationship between a cultural heritage object and its type. It can be used to indicate that an object has the type sculpture, for example. De property heeftType legt de relatie tussen een cultuurhistorisch object en het type vast. The property heeftType establishes the relationship between a cultural heritage object and its type.
    heeftTypeNaam: URIRef  # De property heeftTypenaam legt de relatie tussen het type en de naam van het type met betrekking tot een cultuurhistorisch object vast. The property heeftTypenaam establishes the relationship between the type and the name of the type in relation to a cultural heritage object.
    heeftTypekenmerk: URIRef  # De property heeftTypekenmerk legt de relatie tussen het type en het typekenmerk met betrekking tot een cultuurhistorisch object vast. Het wordt gebruikt om specifieke kenmerken of eigenschappen van een cultuurhistorisch object aan te geven. The property heeftTypekenmerk establishes the relationship between the type and the type characteristic of a cultural heritage object. It is used to indicate specific characteristics or properties of a cultural heritage object. De property heeftTypekenmerk legt de relatie tussen het type en het typekenmerk met betrekking tot een cultuurhistorisch object vast. The property heeftTypekenmerk establishes the relationship between the type and the type characteristic of a cultural heritage object.
    heeftVerblijfsobject: URIRef  # De property heeftVerblijfsobject verwijst naar de verblijfsobjectidentificatie uit de Basisregistratie Adressen en Gebouwen. Het wordt gebruikt om relaties tussen entiteiten in de basisregistratie vast te leggen. The property heeftVerblijfsobject refers to the dwelling object identification from the Basisregistratie Adressen en Gebouwen. It is used to establish relationships between entities in the base registration. De property heeftVerblijfsobject verwijst naar de verblijfsobjectidentificatie uit de Basisregistratie Adressen en Gebouwen. The property heeftVerblijfsobject refers to the dwelling object identification from the Basisregistratie Adressen en Gebouwen.
    heeftVertrouwelijkAanduiding: URIRef  # De eigenschap heeftVertrouwelijkAanduiding legt de relatie tussen het cultuurhistorisch object en de vertrouwelijkheid aanduiding vast. Het geeft aan of het object een vertrouwelijke status heeft. The property heeftVertrouwelijkAanduiding establishes the relationship between the cultural heritage object and the confidentiality indication. It indicates whether the object has a confidential status. De property heeftVertrouwelijkAanduiding legt de relatie tussen het cultuurhistorisch object en de vertrouwelijkheid aanduiding vast. The property heeftVertrouwelijkAanduiding establishes the relationship between the cultural heritage object and the confidentiality indication.
    heeftVerwerving: URIRef  # De property heeftVerwerving legt de relatie tussen de vondst of grondspoor en de verwerving vast. The property heeftVerwerving establishes the relationship between the find or ground trace and the acquisition.
    heeftWerelderfgoedType: URIRef  # De property heeftWerelderfgoedstatus legt de relatie tussen het werelderfgoed object en zijn type vast. Het wordt gebruikt om aan te geven van welk type een bepaald werelderfgoed object is. The property heeftWerelderfgoedstatus establishes the relationship between the World Heritage object and its type. It is used to indicate which type a certain World Heritage object is. De property heeftWerelderfgoedstatus legt de relatie tussen het werelderfgoed object en zijn type vast. The property heeftWerelderfgoedstatus establishes the relationship between the World Heritage object and its type.
    heeftWerelderfgoedstatus: URIRef  # De property heeftWerelderfgoedstatus legt de relatie tussen het werelderfgoed object en zijn status vast. Het wordt gebruikt om aan te geven of een bepaald object de werelderfgoedstatus heeft of niet. The property heeftWerelderfgoedstatus establishes the relationship between the World Heritage object and its status. It is used to indicate whether a certain object has World Heritage status or not. De property heeftWerelderfgoedstatus legt de relatie tussen het werelderfgoed object en zijn status vast. The property heeftWerelderfgoedstatus establishes the relationship between the World Heritage object and its status.
    heeftZaak: URIRef  # De property heeftZaak legt de relatie vast tussen de kennisregistratie en de zaak. The heeftZaak property establishes the relationship between the knowledge registration and the case. De property heeftZaak legt de relatie tussen de kennisregistratie en de zaak vast. The property heeftZaak establishes the relationship between the knowledge registration and the case.
    heeftZekerheidsaanduiding: URIRef  # De property heeftZekerheidsaanduiding legt de relatie tussen het type en de zekerheidsaanduiding met betrekking tot een cultuurhistorisch object vast. Het beschrijft de beveiligingsclassificatie van het object. The property heeftZekerheidsaanduiding establishes the relationship between the type and the security indication of a cultural heritage object. It describes the security classification of the object. De property heeftZekerheidsaanduiding legt de relatie tussen het type en de zekerheidsaanduiding met betrekking tot een cultuurhistorisch object vast. The property heeftZekerheidsaanduiding establishes the relationship between the type and the security indication of a cultural heritage object.
    heeftZuiverheid: URIRef  # De property heeftZuiverheid legt de relatie tussen de stijl en cultuur en de zuiverheid met betrekking tot een cultuurhistorisch object vast. The property heeftZuiverheid establishes the relationship between style and culture and the purity regarding a cultural heritage object.
    hoofdfunctie: URIRef  # De property hoofdfunctie wordt gebruikt om aan te geven of een functie de hoofdfunctie van een Cultuurhistorisch Object is. Deze eigenschap heeft een waardebereik van booleaanse waarden (true of false). Wanneer een functie als hoofdfunctie wordt gemarkeerd, geeft dit aan dat het Cultuurhistorisch Object primair geassocieerd is met die functie. The main function property is used to indicate whether a function is the main function of a Cultural Heritage Object. This property has a value range of boolean values (true or false). When a function is marked as the main function, it indicates that the Cultural Heritage Object is primarily associated with that function. De property hoofdfunctie wordt gebruikt om aan te geven of een functie de hoofdfunctie van een Cultuurhistorisch Object is. The main function property is used to indicate whether a function is the main function of a Cultural Heritage Object.
    hoortBijZaak: URIRef  # De eigenschap hoortBijZaak legt de relatie tussen kennisregistratie en zaak vast. Het geeft aan dat een kennisregistratie hoort bij een bepaalde zaak. The hoortBijZaak property establishes the relationship between knowledge registration and case. It indicates that a knowledge registration belongs to a particular case. De property hoortBijZaak legt de relatie tussen kennisregistratie en zaak vast. The property hoortBijZaak establishes the relationship between knowledge registration and case.
    huidigeNaam: URIRef  # Deze eigenschap geeft aan of de naam van het cultuurhistorisch object de huidige naam is. This property indicates whether the name of the cultural heritage object is the current name. De property huidigeNaam wordt gebruikt om aan te geven of de naam, de huidige naam is van een cultuurhistorisch object. The property huidigeNaam is used to indicate whether the name is the current name of a cultural heritage object.
    huisnummer: URIRef  # De property huisnummer wordt gebruikt om het huisnummer, huisletter en huisnummertoevoeging aan te geven van een cultuurhistorisch object. The property huisnummer is used to indicate the house number, house letter, and house number addition of a cultural heritage object. De property huisnummer is een registergegeven binnen de class Rijksmonument. The property huisnummer is a registry data within the class Rijksmonument.
    inProceduredatumGezicht: URIRef  # Specifies the date on which the townscape enters a procedural stage or process. Geeft de datum aan waarop het gezicht een procedurele fase of proces ingaat. De property inProceduredatumGezicht wordt gebruikt om aan te geven de in proceduredatum van het Gezicht. Dit predicaat is tijdelijk, in de toekomst moet dit worden gemodelleerd in de Zaak Ontologie. The property inProceduredatumGezicht is used to indicate the in-procedure date of the townscape.
    indicatieArcheologischeMonumentenKaartWaardig: URIRef  # Geeft aan of het archeologisch onderzoeksgebied AMK waardig is. Indicates whether the archaeological research area is AMK worthy. De property indicatieArcheologischeMonumentenKaartWaardig wordt gebruikt om aan te geven of een archeologisch onderzoeksgebied AMK waardig is. The property indicatieArcheologischeMonumentenKaartWaardig is used to indicate whether an archaeological research area is AMK worthy.
    internationaalKenteken: URIRef  # De property internationaalKenteken wordt gebruikt om aan te geven of een internationaal kenteken aan een Cultuurhistorisch object is gegeven. Bijvoorbeeld, als een Cultuurhistorisch object internationaal erkend is, kan het de status 'true' hebben voor deze property. The property internationaalKenteken is used to indicate whether a distictive emblem has been assigned to a Cultural Heritage object. For instance, if a Cultural Heritage object is internationally recognized, it can have a 'true' value for this property. De property internationaalKenteken wordt gebruikt om aan te geven of een internationaal kenteken aan een Cultuurhistorisch object is gegeven. The property internationaalKenteken is used to indicate whether a distinctive emblem has been assigned to a Cultural Heritage object.
    intrekkingsdatumGezicht: URIRef  # A property indicating the date on which the townscape is withdrawn. Een eigenschap die de datum aangeeft waarop het gezicht wordt ingetrokken. De property intrekkingsdatumGezicht wordt gebruikt om aan te geven de intrekkingsdatum van het Gezicht. The property intrekkingsdatumGezicht is used to indicate the withdrawal date of the townscape.
    isHoofdobjectVanComplex: URIRef  # De property isHoofdobjectVanComplex legt de relatie tussen een rijksmonument en het hoofdobject met betrekking tot een complex vast. Het hoofdobject van een complex is het belangrijkste object binnen dat complex. The isHoofdobjectVanComplex property defines the relationship between a national monument and the main object related to a complex. The main object of a complex is the most significant object within that complex. De property isHoofdobjectVanComplex legt de relatie tussen een rijksmonument en het hoofdobject met betrekking tot een complex vast. The isHoofdobjectVanComplex property defines the relationship between a national monument and the main object related to a complex.
    isKennisregistratieVanZaak: URIRef  # De property isKennisregistratieVanZaak legt de relatie tussen een zaak en de kennisregistratie van die zaak vast. Het geeft aan welke kennisregistratie betrekking heeft op een bepaalde zaak. The property isKennisregistratieVanZaak establishes the relationship between a case and the knowledge registration associated with that case. It indicates which knowledge registration is related to a specific case. De property isKennisregistratieVanZaak legt de relatie tussen zaak en kennisregistratie vast. The property isKennisregistratieVanZaak establishes the relationship between case and knowledge registration.
    isOnderdeelVanComplex: URIRef  # De property isOnderdeelVanComplex legt de relatie tussen het rijksmonument als onderdeel van een complex vast. The isOnderdeelVanComplex property establishes the relationship between the national monument as part of a complex.
    jaarVanInschrijving: URIRef  # This property represents the year in which a cultural-historical object was registered. Deze property geeft het jaar aan waarin een cultuurhistorisch object is ingeschreven. The property jaarVanInschrijving is used to indicate the year of registration of a cultural-historical object. The property jaarVanInschrijving is used to specify the year of registration of a cultural-historical object.
    kaartbladcode: URIRef  # Een kaartbladcode is een code die wordt gebruikt om een specifiek kaartblad of een deel daarvan aan te duiden. A card code is a code used to identify a specific map sheet or a part thereof. De property kaartbladcode wordt gebruikt om aan te geven welke kaartbladcode is gekoppeld aan de locatie aanduiding. The property card code is used to indicate the associated card code of the location identifier.
    kadasterdeel: URIRef  # De property kadasterdeel wordt gebruikt om aan te geven het kadasterdeel waaronder het rijksmonument bekend is. Voorbeeldelement: 82650 The property kadasterdeel is used to indicate the cadastral plot under which the national monument is known. Example element: 82650 De property kadasterdeel wordt gebruikt om aan te geven het kadasterdeel waaronder het rijksmonument bekend is. The property kadasterdeel is used to indicate the cadastral plot under which the national monument is known.
    kadasterdeelnummer: URIRef  # Eigenschap voor het weergeven van het kadasterdeelnummer van het rijksmonument. Property for indicating the cadastral plot number of the national monument. De property kadasterdeelnummer wordt gebruikt om aan te geven het kadasterdeelnummer waaronder het rijksmonument bekend is. The property kadasterdeelnummer is used to indicate the cadastral plot number under which the national monument is known.
    kadastraleGemeentecode: URIRef  # De naam van de kadastrale gemeente. The name of the cadastral municipality. De property kadastraleGemeentecode is een registergegeven binnen de class Rijksmonument. De property kadastraleGemeentecode wordt gebruikt om aan te geven of een kadastrale gemeente code is toegewezen aan een rijksmonument.
    kennisregistratieToelichting: URIRef  # Dit is een eigenschap die wordt gebruikt om de toelichting op de kennisregistratie-instantie vast te leggen. Het beschrijft het doel of de inhoud van de kennisregistratie. This is a property used to capture the explanation of the knowledge registration instance. It describes the purpose or content of the knowledge registration. De property kennisegistratieToelichting wordt gebruikt om aan te geven de toelichting op de kennisregistratie instance. The property kennisregistratieToelichting is used to indicate the explanation of the knowledge registration instance.
    kennisregistratienummer: URIRef  # Dit is het unieke nummer waaronder de kennisregistratie instance bekend is: 5177345. This is the unique number under which the knowledge registration instance is known: 5177345. De property kennisregistratienummer wordt gebruikt om aan te geven het unieke nummer waaronder de kennisregistratie instance bekend is. The property kennisregistratienummer is used to indicate the unique number under which the knowledge registration instance is known.
    ligtInObject: URIRef  # De eigenschap ligtInObject legt de relatie tussen de ligging van een cultuurhistorisch object met betrekking tot een cultuurhistorisch object vast. Deze eigenschap wordt gebruikt om de ruimtelijke relatie tussen objecten in een erfgoedcontext te modelleren. The ligtInObject property establishes the relationship between the location of a cultural heritage object in relation to another cultural heritage object. This property is used to model the spatial relationship between objects in a heritage context. De property ligtInObject legt de relatie tussen de ligging van een cultuurhistorisch object met betrekking tot een cultuurhistorisch object vast. The ligtInObject property establishes the relationship between the location of a cultural heritage object in relation to another cultural heritage object.
    locatieAanduidingnummer: URIRef  # Een datatype-eigenschap die wordt gebruikt om het unieke nummer waaronder de locatieaanduiding-instantie bekend is, aan te geven. A datatype property used to indicate the unique number under which the location indication instance is known. De property locatieAanduidingnummer wordt gebruikt om aan te geven het unieke nummer waaronder de locatie aanduiding instance bekend is. The property locatieAanduidingnummer is used to indicate the unique number under which the location indication instance is known.
    locatienaam: URIRef  # Deze eigenschap geeft de naam van de locatie weer. Het datatype is een string. This property represents the name of the location. The datatype is string. De property locatienaam wordt gebruikt om aan te geven welke locatie naam is gekoppeld aan de locatie aanduiding The property locatienaam is used to indicate the location name linked to the location indication
    locatieomschrijving: URIRef  # De property locatieomschrijving wordt gebruikt om aan te geven de locatie registratie van een rijksmonument, wanneer het rijksmonument geen 'verblijfsobject' in de BAG is. The property locatieomschrijving is used to indicate the location registration of a national monument when the national monument is not a 'verblijfsobject' in the BAG (the Dutch Building and Address Database).
    naam: URIRef  # De naam van het cultuurhistorisch object. The name of the cultural heritage object. De property naam is een registergegeven binnen de class Rijksmonument. De property naam wordt gebruikt om aan te geven de naam van het cultuurhistorisch object. The property naam is a registry data within the class Rijksmonument. The property naam is used to indicate the name of the cultural heritage object.
    omschrijving: URIRef  # Een tekstuele beschrijving van een cultuurhistorisch object. A textual description of a cultural heritage object. De property omschrijving wordt gebruikt om aan te geven de omschrijving van een cultuurhistorisch object. The property omschrijving is used to indicate the description of a cultural heritage object.
    openbareRuimte: URIRef  # De openbare ruimte waarin het cultuurhistorisch object zich bevindt. The public space in which the cultural heritage object is located. De property openbareRuimte wordt gebruikt om aan te geven de openbare ruimte van een cultuurhistorisch object. De property openbareRuimte is een registergegeven binnen de class Rijksmonument. The property openbareRuimte is used to indicate the public space of a cultural heritage object. The property openbareRuimte is a registry data within the class Rijksmonument.
    oppervlakteInHectare: URIRef  # This property represents the surface area in hectares of a cultural-historical object. Deze property vertegenwoordigt de oppervlakte in hectare van een cultuurhistorisch object en is bedoeld voor gebruik door zowel ontwikkelaars als niet-ontwikkelaars. De property oppervlakteInHectare wordt gebruikt om aan te geven de oppervlakte in hectare van een cultuurhistorisch object. The property oppervlakteInHectare is used to indicate the surface area in hectares of a cultural-historical object.
    oppervlakteInVierkanteKilometers: URIRef  # This property represents the surface area in square kilometers of a cultural-historical object. Deze property vertegenwoordigt de oppervlakte in vierkante kilometers van een cultuurhistorisch object en is bedoeld om toegankelijker te zijn voor niet-ontwikkelaars. De property oppervlakteInVierkanteKilometers wordt gebruikt om aan te geven de oppervlakte in vierkante kilometers van een cultuurhistorisch object. The property oppervlakteInVierkanteKilometers is used to indicate the surface area in square kilometers of a cultural-historical object.
    oppervlakteInVierkanteMeters: URIRef  # This property represents the area in square meters of a cultural-historical object. Deze property vertegenwoordigt de oppervlakte in vierkante meters van een cultuurhistorisch object. Het is bedoeld om toegankelijker te zijn voor niet-ontwikkelaars. De property oppervlakteInVierkanteMeters wordt gebruikt om aan te geven de oppervlakte in vierkante meters van een cultuurhistorisch object. The property oppervlakteInVierkanteMeters is used to indicate the area in square meters of a cultural-historical object.
    pandIdentificatie: URIRef  # Een unieke identificatie van een pand gekoppeld aan de Basisregistratie Adressen en Gebouwen. A unique identification of a building linked to the Basisregistratie Adressen en Gebouwen. De property pandIdentificatie wordt gebruikt om aan te geven welke pand identificatie aan de Basisregistratie Adressen en Gebouwen is gekoppeld. The property pandIdentificatie is used to indicate which building identification is linked to the Basisregistratie Adressen en Gebouwen.
    perceelnummer: URIRef  # De property perceelnummer wordt gebruikt om aan te geven of het nummer dat aan een geheel perceel of een complex, uniek identificeert wordt binnen de sectie. The property plot number is used to indicate whether the number attached to an entire plot or a complex, uniquely identifies it within the section. De property perceelnummer is een registergegeven binnen de class Rijksmonument. The property plot number is a registry entry within the class Rijksmonument.
    plaatscode: URIRef  # Een code die de plaats aangeeft waaraan het rijksmonument is gekoppeld. A code indicating the place to which the national monument is linked. De property plaatsCode wordt gebruikt om aan te geven welke plaats code is gekoppeld aan het rijksmonument. The property placeCode is used to indicate which place code is linked to the national monument.
    postcode: URIRef  # De postcode van de locatie van het cultuurhistorisch object. The postcode of the location of the cultural heritage object. De property postcode is een registergegeven binnen de class Rijksmonument. De property postcode wordt gebruikt om aan te geven de postcode van een cultuurhistorisch object. The property postcode is a registry data within the class Rijksmonument. The property postcode is used to indicate the postcode of a cultural heritage object.
    provinciecode: URIRef  # De provinciecode is een stringwaarde die de code van de provincie waar het rijksmonument zich bevindt, aangeeft. The province code is a string value that indicates the code of the province where the national monument is located. De property provincieCode wordt gebruikt om aan te geven welke provincie code is gekoppeld aan het rijksmonument. The property provinceCode is used to indicate which province code is linked to the national monument.
    registergegeven: URIRef  # Een boolean-waarde die aangeeft of de property een registergegeven is. A boolean value indicating whether the property is a registry data. De property is alleen van toepassing binnen de class Rijksmonument. De property registergegeven wordt gebruikt om aan te geven of een property een registergegeven is. The property registergegeven is only applicable within the class Rijksmonument. The property registergegeven is used to indicate whether a property is a registry data.
    registratiedatum: URIRef  # De registratiedatum property geeft de datum aan waarop de kennisregistratie is geregistreerd. The registratiedatum property indicates the date when the knowledge registration was recorded. De property registratiedatum wordt gebruikt om aan te geven de registratiedatum van de kennisregistratie. The registratiedatum property is used to indicate the registration date of the knowledge registration.
    rijksmonumentnummer: URIRef  # Het rijksmonumentnummer is een registergegeven binnen de class Rijksmonument. De property rijksmonumentnummer wordt gebruikt om aan te geven het unieke nummer waaronder het rijksmonument bekend is in het monumentenregister. The property rijksmonumentnummer is a registry data within the class Rijksmonument. The property rijksmonumentnummer is used to indicate the unique number under which the national monument is known in the monument register.
    sectie: URIRef  # De property sectie wordt gebruikt om de sectie binnen een perceel aan te geven, zoals gedefinieerd in de BRK-registratie. The property sectie is used to indicate the section within a plot, as defined in the BRK registration. The property sectie is used to indicate the section within a plot. The property sectie is a registry item within the Rijksmonument class. De property sectie wordt gebruikt om de sectie binnen een perceel aan te geven. De property sectie is een registergegeven binnen de class Rijksmonument.
    verblijfsobjectIdentificatie: URIRef  # Deze eigenschap geeft de identificatie van het verblijfsobject weer zoals vastgelegd in de Basisregistratie Adressen en Gebouwen. This property represents the identification of the residential object as recorded in the Basisregistratie Adressen en Gebouwen. De property verblijfsobjectIdentificatie wordt gebruikt om aan te geven welke verblijfsobject identificatie aan de Basisregistratie Adressen en Gebouwen is gekoppeld. The property verblijfsobjectIdentificatie is used to indicate which residential object identification is linked to the Basisregistratie Adressen en Gebouwen.
    volledigAdres: URIRef  # De property volledigAdres wordt gebruikt om aan te geven het volledige adres van een cultuurhistorisch object. The property volledigAdres is used to indicate the full address of a cultural heritage object.
    werelderfgoednummer: URIRef  # Een uniek nummer dat wordt gebruikt om dit specifieke werelderfgoed te identificeren. A unique number used to identify this specific world heritage. De property werelderfgoednummer wordt gebruikt om aan te geven het unieke nummer waaronder het werelderfgoed bekend is. The property werelderfgoednummer is used to indicate the unique number under which the world heritage is known.
    woonplaatsnaam: URIRef  # De property woonplaatsnaam wordt gebruikt om de woonplaats van een cultuurhistorisch object aan te geven, zoals geregistreerd in de Basisregistratie Adressen en Gebouwen (BAG). The property woonplaatsnaam is used to indicate the place of residence of a cultural heritage object, as registered in the Basisregistratie Adressen en Gebouwen (BAG). De property woonplaatsnaam wordt gebruikt om de woonplaats van een cultuurhistorisch object aan te geven. De property woonplaatsnaam is een registergegeven binnen de class Rijksmonument. The property woonplaatsnaam is used to indicate the place of residence of a cultural heritage object. The property woonplaatsnaam is a registry item within the Rijksmonument class.
    wordtGetoondOp: URIRef  # De property wordtGetoondOp wordt gebruikt om het webadres van een resource van een cultuurhistorisch object aan te geven. The property isShownAt is used to specify the web address of a resource related to a cultural heritage object.

    # Valid non-python identifiers
    _extras = [
        "asWKT-RD",  # De property asWKT-RD wordt gebruikt om de geometrie volgens EPSG:28992; het Rijksdriehoekstelsel (RD) van een cultuurhistorisch object aan te geven. The property asWKT-RD is used to indicate the geometry of a cultural heritage object in EPSG:28992; the Dutch Rijksdriehoekstelsel (RD) coordinate system. De geometrie is een registergegeven binnen de class Rijksmonument. The geometry is a registry item within the Rijksmonument class.
    ]
