import unittest
import Levenshtein
import batch_add_pages
import batch_edit_pages


class TestStringMethods(unittest.TestCase):
    """Test class for batch_update_wikitext."""

    def test_dont_add(self):
        """add_field mag geen edits doen""" 
        testdata = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Batch=kastelen-complexonderdelen-202506', '|Status=Publiceren', '|Monumentnummer=403621', '|Complex=Nee', '|Plaatsnaam=Lochem', '|Adres=Bij Laan Ampsen 8', '|Naam monument=Historische tuin- en parkaanleg', '|Introductie=Historische tuin- en parkaanleg van de buitenplaats Ampsen.', '|Kenmerken=* Datering: 18de, 19de eeuw', '* Rijksmonument sinds: 22 april 1993', '|Omschrijving={{Monumenten - Onderdeel complex|401776}}', '{{Monumenten - Kennis in register}}', '|Afbeelding (extern)={{Afbeelding|bestand=Ampsen-achter.jpg|bijschrift=Kasteelbeer, [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Het huis centraal op de foto te midden van een grasveld.}}', '|Gerelateerd aan monument=Complexen/401776', '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan gezicht=Gezicht/3333|Gerelateerd aan thema=Thema/Monumenten', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst (1908-1933)', '|Bron=https://www.dbnl.org/tekst/_voo016voor02_01/_voo016voor02_01_0076.php', '|Bron text=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst. Deel IV. De provincie Gelderland - Lochem. (1917)', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Bibliotheek RCE', '|Bron=https://catalogus.cultureelerfgoed.nl/search/detail?database=fullCatalogue&fieldname=Field_MonumentNumber&value=403621', '|Bron text=Publicatie(s) over dit rijksmonument', '}}'])
        with self.assertRaises(AssertionError) as context:
                    batch_add_pages.add_field(''.join(testdata), 'Gerelateerd aan gezicht', 'Gezicht/1409')
                    self.assertTrue('niet leeg' in str(context.exception))

    def test_add_field(self):
        """volledige pagina add_field test"""
        testdata = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Batch=kastelen-complexonderdelen-202506', '|Status=Publiceren', '|Monumentnummer=403621', '|Complex=Nee', '|Plaatsnaam=Lochem', '|Adres=Bij Laan Ampsen 8', '|Naam monument=Historische tuin- en parkaanleg', '|Introductie=Historische tuin- en parkaanleg van de buitenplaats Ampsen.', '|Kenmerken=* Datering: 18de, 19de eeuw', '* Rijksmonument sinds: 22 april 1993', '|Omschrijving={{Monumenten - Onderdeel complex|401776}}', '{{Monumenten - Kennis in register}}', '|Afbeelding (extern)={{Afbeelding|bestand=Ampsen-achter.jpg|bijschrift=Kasteelbeer, [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Het huis centraal op de foto te midden van een grasveld.}}', '|Gerelateerd aan monument=Complexen/401776', '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan gezicht=|Gerelateerd aan thema=Thema/Monumenten', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst (1908-1933)', '|Bron=https://www.dbnl.org/tekst/_voo016voor02_01/_voo016voor02_01_0076.php', '|Bron text=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst. Deel IV. De provincie Gelderland - Lochem. (1917)', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Bibliotheek RCE', '|Bron=https://catalogus.cultureelerfgoed.nl/search/detail?database=fullCatalogue&fieldname=Field_MonumentNumber&value=403621', '|Bron text=Publicatie(s) over dit rijksmonument', '}}'])
        expected = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Batch=kastelen-complexonderdelen-202506', '|Status=Publiceren', '|Monumentnummer=403621', '|Complex=Nee', '|Plaatsnaam=Lochem', '|Adres=Bij Laan Ampsen 8', '|Naam monument=Historische tuin- en parkaanleg', '|Introductie=Historische tuin- en parkaanleg van de buitenplaats Ampsen.', '|Kenmerken=* Datering: 18de, 19de eeuw', '* Rijksmonument sinds: 22 april 1993', '|Omschrijving={{Monumenten - Onderdeel complex|401776}}', '{{Monumenten - Kennis in register}}', '|Afbeelding (extern)={{Afbeelding|bestand=Ampsen-achter.jpg|bijschrift=Kasteelbeer, [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Het huis centraal op de foto te midden van een grasveld.}}', '|Gerelateerd aan monument=Complexen/401776', '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan gezicht=Gezicht/1409|Gerelateerd aan thema=Thema/Monumenten', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst (1908-1933)', '|Bron=https://www.dbnl.org/tekst/_voo016voor02_01/_voo016voor02_01_0076.php', '|Bron text=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst. Deel IV. De provincie Gelderland - Lochem. (1917)', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Bibliotheek RCE', '|Bron=https://catalogus.cultureelerfgoed.nl/search/detail?database=fullCatalogue&fieldname=Field_MonumentNumber&value=403621', '|Bron text=Publicatie(s) over dit rijksmonument', '}}'])
        result = batch_add_pages.add_field(testdata, 'Gerelateerd aan gezicht', 'Gezicht/1409')
        self.assertTrue(Levenshtein.ratio(testdata, expected) == Levenshtein.ratio(testdata, result), msg=f"\nGot \n{result} \nexpected \n{expected}")   

    def test_add_field_value_bottom(self):
        """add_field moet kunnen omgaan met newlines aan het eind van document""" 
        testdata = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Status=Publiceren', '|Monumentnummer=11559', '|Batch=202411-advies-PLOOI', 
                    '|Complex=Nee', '|Plaatsnaam=Culemborg', '|Adres=Markt 11', '|Introductie=Woonhuis in Culemborg.', '|Kenmerken=* Datering: 1549', 
                    '* Rijksmonument sinds: 11 juni 1975', '|Omschrijving===Aanleiding voor de bescherming==', 'Het pand is ingeschreven in het rijksmonumentenregister in de eerste tranche na de inwerkingtreding van de Monumentenwet 1961.', 
                    '|Afbeelding (extern)={{Afbeelding|bestand=T.T Herenhuis Markt 11 Culemborg 1.jpg|bijschrift=Afb. 1. Foto door MHB Verkuijlen, januari 2002. [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Foto van de voorgevel van het bakstenen huis met fietsen en traditionele lantaarnpaal ervoor.}}', 
                    '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan thema=Thema/Monumenten', '|Gerelateerd aan gezicht=', '}}'])
        expected = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Status=Publiceren', '|Monumentnummer=11559', '|Batch=202411-advies-PLOOI', 
                    '|Complex=Nee', '|Plaatsnaam=Culemborg', '|Adres=Markt 11', '|Introductie=Woonhuis in Culemborg.', '|Kenmerken=* Datering: 1549', 
                    '* Rijksmonument sinds: 11 juni 1975', '|Omschrijving===Aanleiding voor de bescherming==', 'Het pand is ingeschreven in het rijksmonumentenregister in de eerste tranche na de inwerkingtreding van de Monumentenwet 1961.', 
                    '|Afbeelding (extern)={{Afbeelding|bestand=T.T Herenhuis Markt 11 Culemborg 1.jpg|bijschrift=Afb. 1. Foto door MHB Verkuijlen, januari 2002. [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Foto van de voorgevel van het bakstenen huis met fietsen en traditionele lantaarnpaal ervoor.}}', 
                    '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan thema=Thema/Monumenten', '|Gerelateerd aan gezicht=Gezicht/1409', '}}'])
        result = batch_add_pages.add_field(testdata, 'Gerelateerd aan gezicht', 'Gezicht/1409')
        self.assertTrue(Levenshtein.ratio(testdata, expected) == Levenshtein.ratio(testdata, result), msg=f"\nGot \n{result} \nexpected \n{expected}") 

    def test_dont_edit(self):
        """add_field mag geen edits doen"""
        testdata = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Batch=kastelen-complexonderdelen-202506', '|Status=Publiceren', '|Monumentnummer=403621', '|Complex=Nee', '|Plaatsnaam=Lochem', '|Adres=Bij Laan Ampsen 8', '|Naam monument=Historische tuin- en parkaanleg', '|Introductie=Historische tuin- en parkaanleg van de buitenplaats Ampsen.', '|Kenmerken=* Datering: 18de, 19de eeuw', '* Rijksmonument sinds: 22 april 1993', '|Omschrijving={{Monumenten - Onderdeel complex|401776}}', '{{Monumenten - Kennis in register}}', '|Afbeelding (extern)={{Afbeelding|bestand=Ampsen-achter.jpg|bijschrift=Kasteelbeer, [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Het huis centraal op de foto te midden van een grasveld.}}', '|Gerelateerd aan monument=Complexen/401776', '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan gezicht=|Gerelateerd aan thema=Thema/Monumenten', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst (1908-1933)', '|Bron=https://www.dbnl.org/tekst/_voo016voor02_01/_voo016voor02_01_0076.php', '|Bron text=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst. Deel IV. De provincie Gelderland - Lochem. (1917)', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Bibliotheek RCE', '|Bron=https://catalogus.cultureelerfgoed.nl/search/detail?database=fullCatalogue&fieldname=Field_MonumentNumber&value=403621', '|Bron text=Publicatie(s) over dit rijksmonument', '}}'])
        with self.assertRaises(AssertionError) as context:
            batch_edit_pages.edit_field(testdata, 'Gerelateerd aan gezicht', 'Gezicht/1409')
            self.assertTrue('is leeg' in str(context.exception))

    def test_dont_edit_missing_field(self):
        """veld ontbreekt test"""
        testdata = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Batch=kastelen-complexonderdelen-202506', '|Status=Publiceren', '|Monumentnummer=403621', '|Complex=Nee', '|Plaatsnaam=Lochem', '|Adres=Bij Laan Ampsen 8', '|Naam monument=Historische tuin- en parkaanleg', '|Introductie=Historische tuin- en parkaanleg van de buitenplaats Ampsen.', '|Kenmerken=* Datering: 18de, 19de eeuw', '* Rijksmonument sinds: 22 april 1993', '|Omschrijving={{Monumenten - Onderdeel complex|401776}}', '{{Monumenten - Kennis in register}}', '|Afbeelding (extern)={{Afbeelding|bestand=Ampsen-achter.jpg|bijschrift=Kasteelbeer, [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Het huis centraal op de foto te midden van een grasveld.}}', '|Gerelateerd aan monument=Complexen/401776', '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan thema=Thema/Monumenten', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst (1908-1933)', '|Bron=https://www.dbnl.org/tekst/_voo016voor02_01/_voo016voor02_01_0076.php', '|Bron text=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst. Deel IV. De provincie Gelderland - Lochem. (1917)', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Bibliotheek RCE', '|Bron=https://catalogus.cultureelerfgoed.nl/search/detail?database=fullCatalogue&fieldname=Field_MonumentNumber&value=403621', '|Bron text=Publicatie(s) over dit rijksmonument', '}}'])
        with self.assertRaises(AssertionError) as context:
            batch_edit_pages.edit_field(testdata, 'Gerelateerd aan gezicht', 'Gezicht/1409')
            self.assertTrue('ontbreekt' in str(context.exception))

    def test_dont_edit_empty_field(self):
        """veld is leeg test"""
        testdata = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Batch=kastelen-complexonderdelen-202506', '|Status=Publiceren', '|Monumentnummer=403621', '|Complex=Nee', '|Plaatsnaam=Lochem', '|Adres=Bij Laan Ampsen 8', '|Naam monument=Historische tuin- en parkaanleg', '|Introductie=Historische tuin- en parkaanleg van de buitenplaats Ampsen.', '|Kenmerken=* Datering: 18de, 19de eeuw', '* Rijksmonument sinds: 22 april 1993', '|Omschrijving={{Monumenten - Onderdeel complex|401776}}', '{{Monumenten - Kennis in register}}', '|Afbeelding (extern)={{Afbeelding|bestand=Ampsen-achter.jpg|bijschrift=Kasteelbeer, [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Het huis centraal op de foto te midden van een grasveld.}}', '|Gerelateerd aan monument=Complexen/401776', '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan gezicht=', '|Gerelateerd aan thema=Thema/Monumenten', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst (1908-1933)', '|Bron=https://www.dbnl.org/tekst/_voo016voor02_01/_voo016voor02_01_0076.php', '|Bron text=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst. Deel IV. De provincie Gelderland - Lochem. (1917)', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Bibliotheek RCE', '|Bron=https://catalogus.cultureelerfgoed.nl/search/detail?database=fullCatalogue&fieldname=Field_MonumentNumber&value=403621', '|Bron text=Publicatie(s) over dit rijksmonument', '}}'])
        with self.assertRaises(AssertionError) as context:
            batch_edit_pages.edit_field(testdata, 'Gerelateerd aan gezicht', 'Gezicht/1409')
            self.assertTrue('is leeg' in str(context.exception))

    def test_edit(self):
        """Testing a actual full page."""
        testdata = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Batch=kastelen-complexonderdelen-202506', '|Status=Publiceren', '|Monumentnummer=403621', '|Complex=Nee', '|Plaatsnaam=Lochem', '|Adres=Bij Laan Ampsen 8', '|Naam monument=Historische tuin- en parkaanleg', '|Introductie=Historische tuin- en parkaanleg van de buitenplaats Ampsen.', '|Kenmerken=* Datering: 18de, 19de eeuw', '* Rijksmonument sinds: 22 april 1993', '|Omschrijving={{Monumenten - Onderdeel complex|401776}}', '{{Monumenten - Kennis in register}}', '|Afbeelding (extern)={{Afbeelding|bestand=Ampsen-achter.jpg|bijschrift=Kasteelbeer, [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Het huis centraal op de foto te midden van een grasveld.}}', '|Gerelateerd aan monument=Complexen/401776', '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan gezicht=Gezicht/3333|Gerelateerd aan thema=Thema/Monumenten', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst (1908-1933)', '|Bron=https://www.dbnl.org/tekst/_voo016voor02_01/_voo016voor02_01_0076.php', '|Bron text=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst. Deel IV. De provincie Gelderland - Lochem. (1917)', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Bibliotheek RCE', '|Bron=https://catalogus.cultureelerfgoed.nl/search/detail?database=fullCatalogue&fieldname=Field_MonumentNumber&value=403621', '|Bron text=Publicatie(s) over dit rijksmonument', '}}'])
        expected = '\n'.join(['{{#element:', '|Elementtype=Monument', '|Batch=kastelen-complexonderdelen-202506', '|Status=Publiceren', '|Monumentnummer=403621', '|Complex=Nee', '|Plaatsnaam=Lochem', '|Adres=Bij Laan Ampsen 8', '|Naam monument=Historische tuin- en parkaanleg', '|Introductie=Historische tuin- en parkaanleg van de buitenplaats Ampsen.', '|Kenmerken=* Datering: 18de, 19de eeuw', '* Rijksmonument sinds: 22 april 1993', '|Omschrijving={{Monumenten - Onderdeel complex|401776}}', '{{Monumenten - Kennis in register}}', '|Afbeelding (extern)={{Afbeelding|bestand=Ampsen-achter.jpg|bijschrift=Kasteelbeer, [https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en CC BY-SA 3.0 NL], via Wikimedia Commons|alternatief=Het huis centraal op de foto te midden van een grasveld.}}', '|Gerelateerd aan monument=Complexen/401776', '|Gerelateerd aan artikel=Monumenten', '|Gerelateerd aan gezicht=Gezicht/1409|Gerelateerd aan thema=Thema/Monumenten', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst (1908-1933)', '|Bron=https://www.dbnl.org/tekst/_voo016voor02_01/_voo016voor02_01_0076.php', '|Bron text=Voorloopige lijst der Nederlandsche monumenten van geschiedenis en kunst. Deel IV. De provincie Gelderland - Lochem. (1917)', '}}', '{{SourceDocument', '|Is onderdeel van=Overige bronnen', '|Voorkeurslabel=Bibliotheek RCE', '|Bron=https://catalogus.cultureelerfgoed.nl/search/detail?database=fullCatalogue&fieldname=Field_MonumentNumber&value=403621', '|Bron text=Publicatie(s) over dit rijksmonument', '}}'])
        result = batch_edit_pages.edit_field(testdata, 'Gerelateerd aan gezicht', 'Gezicht/1409')
        self.assertTrue(Levenshtein.ratio(testdata, expected) == Levenshtein.ratio(''.join(testdata), ''.join(result)), msg=f"\nGot \n{''.join(result)} \nexpected \n{''.join(expected)}") 
    
if __name__ == '__main__':
    unittest.main()